# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		expat
PKG_VERSION:=		2.8.5
PKG_RELEASE:=		1
PKG_HASH:=		920dde485e15eda0cce8d2310b41d492c534e5e3d89ad407a0b4176dd2ff88fe
PKG_SITES:=		https://github.com/libexpat/libexpat/releases/download/R_2_8_5/
DISTFILES:=		${PKG_NAME}-${PKG_VERSION}.tar.gz
