# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		expat
PKG_VERSION:=		2.7.5
PKG_RELEASE:=		1
PKG_HASH:=		9931f9860d18e6cf72d183eb8f309bfb96196c00e1d40caa978e95bc9aa978b6
PKG_SITES:=		https://github.com/libexpat/libexpat/releases/download/R_2_7_5/
DISTFILES:=		${PKG_NAME}-${PKG_VERSION}.tar.gz
