# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		expat
PKG_VERSION:=		2.8.1
PKG_RELEASE:=		1
PKG_HASH:=		a52eb72108be160e190b5cafa5bba8663f1313f2013e26060d1c18e26e31067b
PKG_SITES:=		https://github.com/libexpat/libexpat/releases/download/R_2_8_1/
DISTFILES:=		${PKG_NAME}-${PKG_VERSION}.tar.gz
