# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		mpfr
PKG_VERSION:=		4.2.2
PKG_RELEASE:=		1
PKG_HASH:=		b67ba0383ef7e8a8563734e2e889ef5ec3c3b898a01d00fa0a6869ad81c6ce01
PKG_SITES:=		http://www.mpfr.org/mpfr-current/
