# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		libiconv
PKG_VERSION:=		1.18
PKG_RELEASE:=		1
PKG_HASH:=		3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8
PKG_SITES:=		https://ftp.gnu.org/pub/gnu/libiconv/
DISTFILES:=		${PKG_NAME}-${PKG_VERSION}.tar.gz
