#!/bin/sh
#PKG brcm-bluetooth
#INIT 10

case $1 in
autostop) ;;
autostart)
	exec sh $0 start
	;;
start)
	target=$(cat /etc/.adktarget)
	case $target in
	  raspberry-pi3 | raspberry-pi3p)
	    btattach -B /dev/ttyAMA0 -P bcm
	    ;;
	  *)
	    ;;
	esac
	;;
stop)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
