#!/bin/sh
echo Starting OpenADK
mount -t proc proc /proc
mount -t sysfs sys /sys
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /tmp
chmod 1777 /tmp
mkdir /var/log
mkdir /var/tmp
