#!/bin/sh
echo Starting OpenADK
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sys /sys
/bin/mkdir /dev/pts
/bin/mount -t devpts devpts /dev/pts
/bin/mount -t tmpfs tmpfs /tmp
/bin/chmod 1777 /tmp
/bin/mkdir /var/log
/bin/mkdir /var/tmp
